MTNPAK/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crags/', include('crags.urls')),
    path('routes/', include('routes.urls')),
    path('routefinder/', include('routefinder.urls')),
    path('', include('homepage.urls')),
    path('register/', user_views.RegisterUser, name="register"),
    #path('profile/', user_views.UserProfile, name="profile"),
    path('users/', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('unauthorized_URL/', user_views.UnauthorizedURL, name="unauthorized_URL"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crags/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.CragsHome.as_view(), name='crags-home'),
    path('addcrag/', views.AddCrag, name='add-crag'),
    path('<crag_id>/addroute/', views.AddRoute, name='add-route'),
    path('<crag_id>/addroutemulti/', views.AddRouteMulti, name='add-route-multi'),
    path('<crag_id>/', views.CragView.as_view(), name='crag-view'),
    path('<crag_id>/routechoice/', views.RouteChoice, name='route-choice'),
    path('api/<crag_id>/', views.CragMapAPIView.as_view(), name='crag-map-api'),
    path('api/<crag_id>/comment/', views.CragCommentAPI.as_view(), name='crag-comment-api'),
    path('api/<crag_id>/reply/<parent_id>/', views.CragCommentReplyAPI.as_view(), name='crag-comment-reply-api')
]

routes/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.RoutesHome.as_view(), name='routes-home'),
    path('<route_id>/', views.RouteView.as_view(), name='route-view'),
    path(
        'api/<route_id>/comment/',
        views.RouteCommentAPI.as_view(),
        name='route-comment-api',
    ),
    path(
        'api/<route_id>/rate/<score>/',
        views.RouteRatingAPI.as_view(),
        name='rate-route-api',
    ),
    path('<route_id>/addascent/', views.AddAscentToRoute, name='add-ascent-to-route'),
    path('<route_id>/addpitchmulti/', views.AddPitchMulti, name='add-pitch-multi'),
]

ascents/models.py
from django.db import models
from django.contrib.auth.models import User
from routes.models import Route



class Ascent(models.Model):
	route = models.ForeignKey(Route, on_delete=models.CASCADE)
	climber = models.ForeignKey(User, on_delete=models.CASCADE)
	date = models.DateField(auto_now=False)

	def __str__(self):
		#return self.route.rcrag.cname 
		return f"{self.climber} - {self.route.rname} - {self.date}"

comments/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone

class Comment(models.Model):

    # Comment metadata
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Comment author")
    created = models.DateTimeField(verbose_name="Created date and time", editable=False, default=timezone.now)
    updated = models.DateTimeField(verbose_name="Edited date and time", default=timezone.now)
    html_user = models.CharField(verbose_name="User name formatted in html for display", max_length=1000)
    comment_level = models.IntegerField(verbose_name='Comment nest level')
    parent = models.ForeignKey("Comment", on_delete=models.CASCADE, verbose_name="Parent comment", default=None, blank=True, null=True)

    # Comment body
    body = models.TextField(verbose_name="Comment body")

    # Mandatory stuff for Generic relations
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.IntegerField()
    content_object = GenericForeignKey()
    
    def __str__(self):
        return f"{self.user} - {self.body}"

    # Overload save() method to puplated created/updated fields
    def save(self, *args, **kwargs):
        # pylint: disable=E1101
        # if comment object doesn't already exist, set created
        if not self.id:
            self.created = timezone.now()
        # otherwise set modified
        self.modified = timezone.now()

        # set the html user display
        self.html_user = '<a href="' + str(self.user.profile.get_absolute_url()) + '">' + str(self.user.username) + '</a>'

        return super(Comment, self).save(*args, **kwargs)

pitches/models.py
from django.db import models
from grades.models import Grade
from routes.models import Route

class Pitch(models.Model):
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE, verbose_name='Pitch Grade', null=True)
    #pdescription is only shown on the 'pitch' template.
    #if a route only has one pitch, their is no link to a pitch template
    pdescription = models.TextField(verbose_name='Pitch Description', blank=True, default="")
    proute = models.ForeignKey(Route, on_delete=models.CASCADE, verbose_name='Route', null=True)
    length = models.FloatField(verbose_name='Pitch Length', default=0)



    base_unit = models.CharField(max_length=50, verbose_name='P Base_unit')

    def __str__(self):
    	return f"{self.proute} - {self.grade} - {self.length}"

ratings/models.py
from django.db import models
from routes.models import Route
from django.contrib.auth.models import User

class Rating(models.Model):
	user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name='Rating owner')
	route = models.ForeignKey(Route, on_delete=models.CASCADE, verbose_name='Rating route')

	score = models.IntegerField(verbose_name='Rating score', default=0)

	def __str__(self):
		return f"{self.user} - {self.route} - {self.score}"

routes/models.py
from django.db import models
from crags.models import Crag
from grades.models import Grade
from django.contrib.contenttypes.fields import GenericRelation
from comments.models import Comment
from django_quill.fields import QuillField


class Route(models.Model):
    rname = models.CharField(max_length=500, verbose_name='Route Name')
    #rdescription = models.CharField(max_length=10000, verbose_name='Route Description')
    rdescription = QuillField(max_length=10000, verbose_name='Route description')

    ropener = models.CharField(max_length=500, verbose_name='Route Opener')
    rcrag = models.ForeignKey(Crag, on_delete=models.CASCADE, null=True, verbose_name='Crag')
    #In case of multipitch, the highest grade of all pitches
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE, verbose_name='Pitch Grade', null=True)
    
    # equal to pitch length if one pitch, otherwise sum of pitch length
    length = models.FloatField(verbose_name='Route Length', default=0)
    # this should be set once and never changed.
    base_unit = models.CharField(max_length=50, verbose_name='R Base_unit')
    
    rtype = models.CharField(max_length=50, verbose_name="Type of route")
    numpitch = models.CharField(max_length=500, verbose_name='Single or Multi')
    avg_rating = models.FloatField(verbose_name='Average rating', default=0)

    comments = GenericRelation(Comment, related_query_name='route-comments')

    def __str__(self):
        return self.rname


    #function to add rating object to route
    def add_rating(self, user, rating):
        if user.is_authenticated:
            #get users eisting ratings for the route
            existing_ratings = self.rating_set.filter(user=user).count()
            #if there is already a rating
            if existing_ratings == 1:
                #delete that rating
                self.rating_set.get(user=user).delete()
            #If more than 1 rating exists, then something is wrong.
            elif existing_ratings > 1:
                print("errormode")

            #save the current rating.
            rating.save()
            self.rating_set.add(rating)
            ratings_count = self.rating_set.count()
            running_total = 0

            for i in self.rating_set.all():
                running_total+= i.score

            if ratings_count > 0 :
                self.avg_rating = running_total / ratings_count
                self.save()
            else:
                self.avg_rating = 0.0

            return self.avg_rating

    # I need this method for route rating    
    def get_absolute_url(self):
        from django.urls import reverse
        # return the string URL for route-view (in urls.py) using self.id as arg
        return reverse('route-view', args=[str(self.id)])

    def get_api_rate_url(self, score):
        from django.urls import reverse
        return reverse('rate-route-api', args=[str(self.id), score])


    def get_highest_grade(self):        
        all_grades = []
        highest_grade_index = 0
        for pitch in self.pitch_set.all():
            all_grades.append(pitch.grade)
        for i, grade in enumerate(all_grades): 
            if all_grades[highest_grade_index].id > grade.id:
                print("all good")
            elif all_grades[highest_grade_index].id <= grade.id:
                highest_grade_index = i
        print("highest grade is", all_grades[highest_grade_index])
        self.grade = all_grades[highest_grade_index]
        self.save()
        return            

routes/forms.py
from django.forms import ModelForm
from ascents.models import Ascent




class AddAscentToRouteForm(ModelForm):

	class Meta:
		model = Ascent
		#fields = ['route', 'climber', 'date']
		exclude = ['climber', 'route']

routes/admin.py
from django.contrib import admin
from .models import Route


admin.site.register(Route)
#admin.site.register(TradRoute)

routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    name = 'routes'

routes/views.py
from django.shortcuts import render, redirect
from .models import Route
from django.views import generic
from django.shortcuts import get_object_or_404
from routes.forms import AddAscentToRouteForm
from django.contrib.auth.decorators import login_required
from pitches.forms import *
from utils.conversions import convert_units
from ratings.models import Rating
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from comments.forms import AddCommentForm
from django.contrib.auth.decorators import permission_required


#this is the view for a routes home page.
# I have not created a tmeplate for this.
class RoutesHome(generic.ListView):
    template_name = 'routes/routes-home.html'
    model = Route

    def get_queryset(self):
        return Route.objects.all()

#this is the view you get when you click on a route.
class RouteView(generic.DetailView):
    template_name = 'routes/route-view.html'
    model = Route

    def get_object(self):
        #get current route and store in variable
        current_route = get_object_or_404(Route, pk=self.kwargs['route_id'])
        return current_route


    # This is a CBV built in method that you can override to add additional
    # context so, in this case I'm adding the commentform()
    def get_context_data(self, **kwargs):
        context = super(RouteView, self).get_context_data(**kwargs)
        context['comment_form'] = AddCommentForm()
        return context


# this is the comment api for routes. Comments are posted to this
# API endpoint.
class RouteCommentAPI(APIView):
    authentication
    _classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def post(self, request, route_id=None, format=None):
        #print(request.data['csrfmiddlewaretoken'])
        route = get_object_or_404(Route, pk=route_id)
        user = self.request.user
        body = request.data['body']
        route.comments.create(body=body, user=user)
        return Response("success")

class RouteRatingAPI(APIView):
    #make sure authenticated and permitted for api call
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    #routeid and score = None because otherwise it has unepected keyword arg error
    def get(self, request, format=None, route_id=None, score=None):
        route = get_object_or_404(Route, pk=route_id)
        user = self.request.user
        #make rating 
        rating = Rating(score=score, route=route, user=user)
        #add rating to route.abs
        # add_rating returns an average rating.
        return Response(route.add_rating(user, rating))


@login_required
def AddAscentToRoute(request, **kwargs):
    if request.method == 'POST':
        form = AddAscentToRouteForm(request.POST)
        if form.is_valid():
            #route_id = kwargs['route_id']
            #print(form.save(commit=False).date)
            newascent = form.save(commit=False)
            newascent.climber = request.user
            newascent.route = Route.objects.get(pk=kwargs['route_id'])
            newascent.save()
            
            return redirect('route-view', route_id=kwargs['route_id'])
    else:
        #form = AddAscentForm(initial={'climber': request.user})
        form = AddAscentToRouteForm()
    return render(request, 'routes/addascenttoroute.html', {'form': form})


#WHY IS THIS VIEW HERE? OR RATHER WHY ARE ADD ROUTE/MULTI AND ROUTE CHOICE in crags.views?
@login_required
@permission_required('routes.add_route', login_url="/unauthorized_URL/")
@permission_required('pitches.add_pitch', login_url="/unauthorized_URL/")
def AddPitchMulti(request, **kwargs):
    ##SET SESSION PREFERENCE VARIABLES
    try:
        grade_pref = request.session['grade_pref']
        measurement_pref = request.session['measurement_pref']
    except KeyError:
        grade_pref = 'French'
        measurement_pref = 'meters'

    if request.method == 'POST':
        
        # render the correct form with correct fields depending on user_pref
        if grade_pref == "YDS":
            form = AddPitchFormYDSMulti(request.POST)
        elif grade_pref == "French":
            form = AddPitchFormFrenchMulti(request.POST)
        
        

        if form.is_valid():
            newpitch = form.save(commit=False)
            newpitch.proute = Route.objects.get(pk=kwargs['route_id'])
            
            #Set base unit for the new pitch to pref of user adding it.
            newpitch.base_unit = measurement_pref

            #check if ROUTE base unit is equal to base unit of pitch being added
            if newpitch.proute.base_unit == newpitch.base_unit:
                # if equal, add to route length
                newpitch.proute.length += newpitch.length
                
            else:
                # if not equal, convery current pitch length to ROUTE base unit, then add
                newpitch.proute.length += convert_units(newpitch.base_unit, newpitch.proute.base_unit, newpitch.length)

            newpitch.proute.save()
            newpitch.save()

            # Once route is saved, set grade to the highest grade of its pitch_set
            newpitch.proute.get_highest_grade()
            
            return redirect('route-view', route_id=kwargs['route_id'])
    else:
        if grade_pref == "YDS":
            form = AddPitchFormYDSMulti()
        elif grade_pref == "French":
            form = AddPitchFormFrenchMulti()


    return render(request, 'routes/addpitch.html', {'form': form})

routes/templates/routes/addascenttoroute.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block page_title %}
	Add your ascent
{% endblock %}

{% block main_content %}
<div class="col-lg-12 colb">
	<form method = "POST">
		{% csrf_token %}
		{{ form|crispy }}
		<div>
			<button type="submit">
				Add Ascent
			</button>
		</div>
	</form>
</div>
{% endblock %}

routes/templates/routes/addpitch.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block page_title %}
	Add new pitch
{% endblock %}

{% block main_content %}
<div class="col-lg-12 colb">
	<form method = "POST">
		{% csrf_token %}
		{{ form.crispy }}
		<div>
			<button type="submit">
				Add pitch
			</button>
		</div>
	</form>
</div>
{% endblock %}

routes/templates/routes/route-view.html
<!--#####################################################-->
<!--###################### IMPORTS ######################-->
<!--#####################################################-->

{% extends 'base.html' %}
{% load view_filters %}
{% load mathfilters %}
{% load static %}
{% load crispy_forms_tags %}
{% load tz %}



{% block custom_css %}
    	<!--custom CSS for star ratings -->
	<link rel="stylesheet" type="text/css" href="{% static 'ratings/star_rating.css' %}" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'ratings/rating_display.css' %}" rel="stylesheet">
{% endblock %}


<!--#####################################################-->
<!--################# CUSTOM JAVASCRIPT #################-->
<!--#####################################################-->

{% block custom_js %}
	{{ comment_form.media }}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js"></script>
{% endblock %}


<!--#####################################################-->
<!--#################### TITLE BLOCK ####################-->
<!--#####################################################-->

{% block page_title %}
	{{ route.rname }}
{% endblock %}
	
{% block body_title %}
	{{ route.rname }}
{% endblock %}



<!--#####################################################-->
<!--#################### CONTENT BLOCK ##################-->
<!--#####################################################-->


{% block main_content %}
<div class="col-lg-12 colb">

	<p>{{ route.numpitch }} {{ route.rtype }}</p>

	<p id='route-rating'>This route is rated: {{route|inline_rating}} with {{route.rating_set.all.count}} votes</p>



	{{ route|inline_user_rating:user }}	

	<br><br>

	<!-- If the route only has one pitch, display the grade-->
	{% if route.numpitch == 'Singlepitch' %}
		
		<p>This single pitch is {{ route|measurement_display:request }}</p>
		{% for pitch in route.pitch_set.all %}
			<!--CHECK GRADE PREFERENCE AND DISPLAY GRADE ACCORDINGLY -->
			{{ pitch|grade_display:request }}
			{{ pitch|measurement_display:request }}
			{{ pitch|measurement_unit_display:request }}

		{% endfor %}
	{% endif %}


	<!-- Otherwise, if the route has more than one pitch, list pitches-->	
	{% if route.numpitch == 'Multipitch' %}

		<p>This multipitch is {{ route|measurement_display:request }}</p>
		{% for pitch in route.pitch_set.all %}
			<p>
				{{ pitch|grade_display:request }}
				{{ pitch|measurement_display:request }}
				{{ pitch|measurement_unit_display:request }}
				{{ pitch.pdescription }} 
			</p>
		{% endfor %}
	{% endif %}

	<br><br>
	<!-- route description displayed here -->
	<p><b>Description:</b> {{ route.rdescription.html|safe }}</p>


	<!-- display all ascents for the route -->
	{% for ascent in route.ascent_set.all %}
		<p>{{ ascent.date }} <a href="{% url 'profile' username=ascent.climber.username %}">{{ ascent.climber.username }}</a></p>
	{% endfor %}
	
	<!-- add ascent button -->
	<br>
	<h3><a href="{% url 'add-ascent-to-route' route_id=route.id %}">ADD YOUR ASCENT</a></h3>


	<!--If route is multipitch, show add pitch button -->
	{% if route.numpitch == 'Multipitch' and perms.pitches.add_pitch %}
		<h3><a href="{% url 'add-pitch-multi' route_id=route.id %}">Add a pitch</a></h3>
	{% endif %}


	<p>
		<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#comment-collapse" aria-expanded="false" aria-controls="comment-collapse">Show comments</button>

	</p>

	<div class="collapse" id="comment-collapse">
		<!---SHOW COMMENTS -->
		<div class="comment-container">
		{% for comment in route.comments.all %}
			<div class="comment-card card bg-light">
				<div class="card-body" style="padding-top: 0px; padding-bottom: 0px">
					<p>
						<h6 class="card-title">
							{{comment.html_user|safe}} @ {{comment.created}} {{TIME_ZONE}}
						</h6>

						<p class="card-text">
							{{ comment.body}}
						</p>
					</p>
				</div>
			</div>
			<br>
		{% endfor %}
		</div>
		
		<!-- SHOW COMMENT BOX -->
		{% if user.is_authenticated and perms.comments.add_comment %}
			<div class="card bg-light">
				<div class="card-body">
					<form class="comment-form" method="post" data-api="{% url 'route-comment-api' route_id=route.id %}">
						{% csrf_token %}
						{{comment_form|crispy}}
						<input type="submit"></form></input>
					</form>
				</div>
			</div>
		{% endif %}
	</div>

	<!--custom js for star rating updates -->
	<script src="{% static 'ratings/rating_update.js' %}" type="text/javascript"></script>
	<script src="{% static 'comments/comments.js' %}" type="text/javascript"></script>

</div>

{% endblock %}