MTNPAK/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crags/', include('crags.urls')),
    path('routes/', include('routes.urls')),
    path('routefinder/', include('routefinder.urls')),
    path('', include('homepage.urls')),
    path('register/', user_views.RegisterUser, name="register"),
    #path('profile/', user_views.UserProfile, name="profile"),
    path('users/', include('users.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('unauthorized_URL/', user_views.UnauthorizedURL, name="unauthorized_URL"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crags/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.CragsHome.as_view(), name='crags-home'),
    path('addcrag/', views.AddCrag, name='add-crag'),
    path('<crag_id>/addroute/', views.AddRoute, name='add-route'),
    path('<crag_id>/addroutemulti/', views.AddRouteMulti, name='add-route-multi'),
    path('<crag_id>/', views.CragView.as_view(), name='crag-view'),
    path('<crag_id>/routechoice/', views.RouteChoice, name='route-choice'),
    path('api/<crag_id>/', views.CragMapAPIView.as_view(), name='crag-map-api'),
    path('api/<crag_id>/comment/', views.CragCommentAPI.as_view(), name='crag-comment-api'),
    path('api/<crag_id>/reply/<parent_id>/', views.CragCommentReplyAPI.as_view(), name='crag-comment-reply-api')
]

crags/models.py
from django.db import models
from django.contrib.auth.models import User
from djgeojson.fields import PointField
from django.contrib.contenttypes.fields import GenericRelation
from comments.models import Comment
from django_quill.fields import QuillField
from cities.models import City
from utils.spatial import calculate_distance


class Crag(models.Model):
    cname = models.CharField(max_length=500, verbose_name='Name')
    cdescription = QuillField(max_length=50000, verbose_name='Crag description')
    cauthor = models.ForeignKey(  # Many crags can have one author
        User, on_delete=models.CASCADE, verbose_name='Page author')
    location = PointField()
    comments = GenericRelation(Comment, related_query_name='crag-comments')
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name='City')
    toprope = models.CharField(max_length=50, verbose_name='Top rope access')


    def __str__(self):
        return self.cname

    def get_absolute_url(self):
        from django.urls import reverse
        # return the string URL for route-view (in urls.py) using self.id as arg

        return reverse('crag-view', args=[str(self.id)])

    def count_routes(self):
    	return self.route_set.all().count()


    def set_nearest_city(self):
        cities_dict = {}
        cities = City.objects.all()
        for city in cities:
            cities_dict[city.pk] = calculate_distance(self.location, city.location)

        # use dict comprehension to sort dict using the value as the "key" to sort by
        cities_dict_sorted = {k: v for k, v in sorted(cities_dict.items(), key=lambda x: x[1])}  # noqa: E501
        nearest_city_key = next(iter(cities_dict_sorted))

        nearest_city = cities.filter(pk=nearest_city_key).first()
        self.city = nearest_city

        return

crags/forms.py
from django import forms
from django.forms import ModelForm
from routes.models import Route
from .models import Crag
from leaflet.forms.widgets import LeafletWidget





#this is the single pitch add route form. It displays along wiht pitch form
class AddRouteForm(ModelForm):

	
	CHOICES = (
		('Sport', 'Sport'),
		('Trad', 'Trad'),
		('Mixed', 'Mixed'),
		)
	rtype = forms.ChoiceField(choices=CHOICES)
	#rname = forms.CharField()
	#rname.widget.attrs.update({'placeholder': 'something studddpfffid', 'rows':40})

	class Meta:
		model = Route
		fields = ('rname', 'rdescription', 'rtype',)
		#rlength is set equal to pitch length once pitch is created
		#exclude = ['rcrag', 'ropener', 'numpitch', 'length', 'base_unit', 'avg_rating', 'grade']


class AddRouteMultiForm(ModelForm):
	CHOICES = (
		('Sport', 'Sport'),
		('Trad', 'Trad'),
		('Mixed', 'Mixed'),
	)
	rtype = forms.ChoiceField(choices=CHOICES)

	class Meta:
		model = Route
		exclude = ['rcrag', 'ropener', 'length', 'numpitch', 'base_unit', 'avg_rating', 'grade']




class RouteChoiceForm(forms.Form):
	CHOICES = (
		('single', 'single'),
		('multi', 'multi')
	)
	choice = forms.ChoiceField(choices=CHOICES)



class AddCragForm(ModelForm):

	#city = forms.ModelChoiceField(City.objects.all())
	TOPROPE_CHOICES = (
		('No information', 'No information'),
		('No access', 'No access'),
		('Some routes', 'Some routes'),
		('All routes', 'All routes'),
	)
	toprope = forms.ChoiceField(choices=TOPROPE_CHOICES)

	class Meta:
		LEAFLET_WIDGET_ATTRS = {
			'map_height': '500px',
			'map_width': '500px',
		}
		model = Crag
		exclude = ['cauthor', 'city']
		widgets = {'location': LeafletWidget(LEAFLET_WIDGET_ATTRS)}

crags/views.py
from django.shortcuts import render, redirect
from .models import Crag
from comments.models import Comment
from django.views import generic
from django.shortcuts import get_object_or_404
from .forms import AddRouteForm, AddCragForm, RouteChoiceForm, AddRouteMultiForm
from pitches.forms import AddPitchFormYDS, AddPitchFormFrench
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView
from rest_framework.response import Response
from comments.forms import AddCommentForm
from rest_framework import authentication, permissions
from django.contrib.auth.decorators import permission_required


# from rest_framework import authentication, permissions

class CragsHome(generic.ListView):
    template_name = 'crags/crags-home.html'
    model = Crag

    def get_queryset(self):
        return Crag.objects.all()

class CragView(generic.DetailView):
    template_name = 'crags/crag-view.html'
    model = Crag

    def get_object(self):

        return get_object_or_404(Crag, pk=self.kwargs['crag_id'])

    # Add comment form to the context
    def get_context_data(self, **kwargs):
        context = super(CragView, self).get_context_data(**kwargs)
        context['comment_form'] = AddCommentForm()
        return context


class CragCommentAPI(APIView):
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def post(self, request, crag_id=None, format=None):
        crag = get_object_or_404(Crag, pk=crag_id)
        user = self.request.user
        body = request.data['body']
        comment_level = 1
        crag.comments.create(body=body, user=user, comment_level=comment_level)
        return Response("Idk")

class CragCommentReplyAPI(APIView):
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def post(self, request, crag_id=None, parent_id=None, format=None):
        max_comment_level = 4
        crag = get_object_or_404(Crag, pk=crag_id)
        user = self.request.user
        body = request.data['body']
        parent = get_object_or_404(Comment, pk=parent_id)
        
        if parent.comment_level < max_comment_level:
            comment_level = int(parent.comment_level + 1)
        else:
            comment_level = 4
        print("comment parent is " + parent_id)

        crag.comments.create(body=body, user=user, parent=parent, comment_level=comment_level)
        return Response("Idk")


### NEED TO REDO THIS. NOT DRY, COULD ROLL MY OWN SERIALIZER ####
class CragMapAPIView(APIView):
    #authentication_classes = (authentication.SessionAuthentication,)
    #permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, format=None, crag_id=None):
        crag = get_object_or_404(Crag, pk=crag_id)

        ## FUCK DJANGO SERIALIZERS. I'M DOING IT MYSELF ##
        json_list = []
        route_dict = {}
        fields_dict = {}        

        try:
            pref = request.session['grade_pref']
            
            if pref == 'YDS':
                for route in crag.route_set.all():
                    fields_dict = {
                        "name": route.rname,
                        "grade": route.grade.ydsgrade
                    }

                    route_dict = {
                        "pk": route.id,
                        "fields": fields_dict
                    }
                    json_list.append(route_dict)

            elif pref == 'French':
                for route in crag.route_set.all():
                    fields_dict = {
                        "name": route.rname,
                        "grade": route.grade.ggrade
                    }

                    route_dict = {
                        "pk": route.id,
                        "fields": fields_dict
                    }
                    json_list.append(route_dict)

        except KeyError:

            for route in crag.route_set.all():
                fields_dict = {
                    "name": route.rname,
                    "grade": route.grade.ggrade
                }

                route_dict = {
                    "pk": route.id,
                    "fields": fields_dict
                }
                json_list.append(route_dict)

        return Response(json_list)


#IN AddRoute, a route and pitch form are both created since for single
#the route only had 1 pitch. We create the pitch and route here simultatenous
# TODO: add error page (wrong permissions)
@login_required
@permission_required('routes.add_route', login_url="/unauthorized_URL/")
def AddRoute(request, **kwargs):
    if request.method == 'POST':
        form = AddRouteForm(request.POST)

        #Choose view based on user pref     
        if request.session['grade_pref'] == "YDS":
            form2 = AddPitchFormYDS(request.POST)
        elif request.session['grade_pref'] == "French":
            form2 = AddPitchFormFrench(request.POST)


        if form.is_valid() and form2.is_valid():
            newroute = form.save(commit=False)
            newpitch = form2.save(commit=False)
            newroute.ropener = request.user
            newroute.rcrag = Crag.objects.get(pk=kwargs['crag_id'])

            newroute.numpitch = 'Singlepitch'
            # create route variable
            newpitch.proute = newroute
            
            # set base unit for both pitch and route (always equal since single pitch)
            # both are only set once.
            newpitch.base_unit = request.session['measurement_pref']
            newroute.base_unit = request.session['measurement_pref']

            newroute.length = newpitch.length
            newroute.grade = newpitch.grade
            
            newroute.save() 
            newpitch.save()
            return redirect('crag-view', crag_id=kwargs['crag_id'])
    else:
        form = AddRouteForm()
        
        if request.session['grade_pref'] == "YDS":
            form2 = AddPitchFormYDS()
        elif request.session['grade_pref'] == "French":
            form2 = AddPitchFormFrench()


    return render(request, 'crags/addroute.html', {'form': form, 'form2': form2})

#However when adding a multipitch route, we need to first create a route
#with no grade or length field in the form (because those are per pitch)

@login_required
@permission_required('routes.add_route', login_url="/unauthorized_URL/")
def AddRouteMulti(request, **kwargs):
    if request.method == 'POST':
        form = AddRouteMultiForm(request.POST)
        if form.is_valid(): #and form2.is_valid():
            newroute = form.save(commit=False)
            newroute.ropener = request.user
            newroute.rcrag = Crag.objects.get(pk=kwargs['crag_id'])
            newroute.numpitch = 'Multipitch'

            # ROUTE base unit is set only once, when route is added.
            newroute.base_unit = request.session['measurement_pref']

            newroute.save()
            #return redirect('crag-view', crag_id=kwargs['crag_id'])
            return redirect('route-view', route_id=newroute.id)
    else:
        form = AddRouteMultiForm()
    return render(request, 'crags/addroute.html', {'form': form})


#choose between single and multipitch when adding new route.
@login_required
@permission_required('routes.add_route', login_url="/unauthorized_URL/")
def RouteChoice(request, **kwargs):
    if request.method == 'POST':
        form = RouteChoiceForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            choice = cd.get('choice')
            if choice == 'single':
                crag_id=kwargs['crag_id']  # noqa: E225
                return redirect('add-route', crag_id=crag_id)
            elif choice == 'multi':
                crag_id = kwargs['crag_id']
                return redirect('add-route-multi', crag_id=crag_id)
    else:
        form = RouteChoiceForm()
    return render(request, 'crags/routechoice.html', {'form': form})


@login_required
@permission_required('crags.add_crag', login_url="/unauthorized_URL/")
def AddCrag(request, **kwargs):
    if request.method == 'POST':
        form = AddCragForm(request.POST)
        if form.is_valid():
            newcrag = form.save(commit=False)
            newcrag.cauthor = request.user
            newcrag.set_nearest_city()
            newcrag.save()

            return redirect('crags-home')
    else:
        form = AddCragForm()
    return render(request, 'crags/addcrag.html', {'form': form})

crags/templates/crags/addcrag.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load leaflet_tags %}


{% block custom_css %}
	{% leaflet_css plugins="forms" %}

	<style>

		.ql-editor{
    		min-height:200px;
		}

	</style>
{% endblock %}


{% block custom_js %}
	{% leaflet_js plugins="forms" %}
	{{ form.media }}
	<script type="text/javascript">
		window.addEventListener("map:init", function(e) {
			var detail = e.detail;
			detail.map.setView([30.350459, 70.288831], 5);
		}, false);

	</script>
{% endblock %}




{% block page_title %}
	Add a crag
{% endblock %}

{% block main_content %}
<div class="col-lg-12 colb">
	<form method = "POST">
		{% csrf_token %}
		{{ form|crispy }}
		<div>
			<button type="submit">
				Add crag
			</button>
		</div>
	</form>
</div>	
{% endblock %}

crags/templates/crags/addroute.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block custom_js %}
{{ form.media }}
{% endblock %}

{% block custom_css %}
<style>

.ql-editor{
    min-height:200px;
}

</style>
{% endblock %}

{% block page_title %}
	Add a route
{% endblock %}

{% block main_content %}
<div class="col-lg-12 colb">
	<form method = "POST">
		{% csrf_token %}
		{{ form|crispy }}

		{% csrf_token %}
		{{ form2|crispy }}


		<div>
			<button type="submit">
				Add Route
			</button>
		</div>
	</form>
</div>
{% endblock %}

crags/templates/crags/crag-view.html
{% extends 'base.html' %}
{% load static %}
{% load view_filters %}
{% load comment_tags %}
{% load crispy_forms_tags %}
{% load tz %}

{% block custom_css %}
  <!--custom CSS for star ratings -->
	<link rel="stylesheet" type="text/css" href="{% static 'ratings/rating_display.css' %}" rel="stylesheet">
{% endblock %}

{% block custom_js %}
	{{ comment_form.media }}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js"></script>
{% endblock %}

{% block page_title %}
	{{ crag.cname }} 
{% endblock %}

{% block body_title %}
	{{ crag.cname }}
{% endblock %}


{% block main_content %}

<div class="col-lg-12 colb">
	<h2>{{ crag.city.name }}</h2>
		<div class="row">
			<!-- TAB NAVIGATION BAR -->
			<div class="col-lg-6 text-center">
				<span class="float-lg-left">
					<ul class="nav nav-tabs">
						<li class="nav-item">
		    			<a class="nav-link active" data-toggle="tab" href="#general">General</a>
		  			</li>
		  			<li class="nav-item">
		    			<a class="nav-link" data-toggle="tab" href="#routes">Routes</a>
		  			</li>
		  			<li class="nav-item">
		    			<a class="nav-link" data-toggle="tab" href="#map">Map</a>
		  			</li>
					</ul>
				</span>
			</div>

			<!-- Crag maintainer info -->
			<div class="col-lg-6 text-center">
				<span class="float-lg-right">
					Page maintained by: <a href="{% url 'profile' username=crag.cauthor %}">{{ crag.cauthor.first_name }} {{crag.cauthor.last_name}}</a>
				</span>		
			</div>
		</div>

		<!-- Tab content section -->
		<div class="col-lg-12">
			
			<!-- Tab panes -->
			<div class="tab-content">
				
				<!-- GENERAL TAB -->
		  	<div class="tab-pane container active" id="general">
		  		<p><b>Toprope access:</b> {{crag.toprope}}</p>
					<p>{{ crag.cdescription.html|safe}}</p>	
		  	</div>
		  	
		  	<!-- MAP TAB -->
		  	<div class="tab-pane container fade" id="map">
		  	Map here
		  	</div>
		  	
		  	<!-- ROUTES TAB -->
		  	<div class="tab-pane container fade" id="routes">
		  		<!-- list all the routes -->
					{% for route in object.route_set.all %}
					<p>
						<a href="{% url 'route-view' route_id=route.id %}">{{ route.rname }}</a>
						{% for pitch in route.pitch_set.all %}
							{{ pitch|grade_display:request }}
						{% endfor %}
						{{route|inline_rating}}
					</p>	
				{% endfor %}	  	
		  </div>
		</div>

		<br><br><br>

		{% if user.is_authenticated and perms.routes.add_route%}
			<h4><a href="{% url 'route-choice' crag_id=crag.id %}">Add new route</a></h4>
		{% endif %}

		<!-- Comment toggle button -->
		<p>
			<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#comment-collapse" aria-expanded="false" aria-controls="comment-collapse">Show comments</button>
		</p>

		<!-- COLLAPSIBLE COMMENTS BOX -->
		<div class="collapse" id="comment-collapse">
			<!---SHOW COMMENTS -->
			<div class="comment-container">
			{% for comment in crag.comments.all|n_level_comments:1 %}
				<div class="comment-card card bg-light comment-level-{{comment.comment_level}}">
					<div class="card-body" style="padding-top: 0px; padding-bottom: 0px">
						<p>
							<h6 class="card-title">
								{{comment.html_user|safe}} @ {{comment.created}} {{TIME_ZONE}}
							</h6>

							<p class="card-text">
								comment id= {{comment.id}}
								{{ comment.body }}
							</p>
							
							<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#comment-{{comment.id}}" aria-expanded="false" aria-controls="comment-{{comment.id}}">Reply</button>
						</p>
					</div>
					{% for reply in comment.comment_set.all %}
						<p>{{reply}}</p>
					{% endfor %}
				</div>
				<br>
				<!-- COMMENT REPLY BOX GOES HERE -->
				<div class="collapse" id="comment-{{comment.id}}">
					{% if user.is_authenticated and perms.comments.add_comment %}
						<div class="card bg-light">
							<div class="card-body">
								<form class="comment-reply-form" id="form-reply-{{comment.id}}" method="post" data-reply-api="{% url 'crag-comment-reply-api' crag_id=crag.id parent_id=comment.id %}">
									{% csrf_token %}
									{{comment_form|crispy}}
									<input type="submit"></input>
								</form>
							</div>
						</div>
					{% endif %}
				</div>
				<!-- -->
			{% endfor %}
			</div>
						
			<!-- SHOW COMMENT BOX -->
			{% if user.is_authenticated and perms.comments.add_comment %}
				<div class="card bg-light">
					<div class="card-body">
						<form class="comment-form" method="post" data-api="{% url 'crag-comment-api' crag_id=crag.id %}">
							{% csrf_token %}
							{{comment_form|crispy}}
							<input type="submit"></input>
						</form>
					</div>
				</div>
			{% endif %}
		</div>

		<!--custom js for star rating updates -->
		<script src="{% static 'comments/comments.js' %}" type="text/javascript"></script>

	</div>

</div>
{% endblock %}

crags/templates/crags/crags-home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block page_title %}
	Crags
{% endblock %}

{% block body_title %}
	Crags
{% endblock %}




{% block main_content %}
	<div class="col-lg-8 colb">

		{% for crag in crag_list %}
			<h2><a href="{% url 'crag-view' crag_id=crag.id %}">{{ crag.cname }}</a></h2>		
		{% endfor %}

		<br><br><br><br>

		
		{% if user.is_authenticated and perms.crags.add_crag %}
			<h4><a href="{% url 'add-crag' %}">Add a new crag</a></h4>
		{% endif %}
	</div>

{% endblock %}

crags/templates/crags/routechoice.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block page_title %}
	Route type
{% endblock %}

{% block main_content %}
	<div class="col-lg-12 colb">
		<form method = "POST">
			{% csrf_token %}
			{{ form|crispy }}

			<div>
				<button type="submit">
					Submit
				</button>
			</div>
		</form>
	</div>
{% endblock %}